// User reducer types

export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

export const FAIL_RES = "FAIL_RES";
export const SUCCESS_RES = "SUCCESS_RES";
export const LOADING_UI = "LOADING_UI";
export const LOGOUT = "LOGOUT";
export const UPDATE_WRITING_SESSION = "UPDATE_WRITING_SESSION";
export const SAVE_FILE = "SAVE_FILE";
export const UPDATE_FILE = "UPDATE_FILE";
export const CREATE_FILE = "CREATE_FILE";
export const SET_CURRENT_DOCUMENT = "SET_CURRENT_DOCUMENT";
export const GET_DOCUMENTS = "GET_DOCUMENTS";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";
export const SET_FULLSCREEN = "SET_FULLSCREEN";
